version: '3'
services:
 # The Application
  gep-configurations-app:
    image: 196.190.41.213:5000/egov/gep-configurations:v0.0.9
    working_dir: /var/www
    container_name: gep-configurations-app-v0.0.9-1
    volumes:
      - /var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=gep-configurations-db"
    networks:
      - app-network 
    restart: always
    tty: true
#The Web Server
  gep-configurations-web:
    image: 196.190.41.213:5000/egov/gep-configurations-web:v0.0.9
    ports:
      - 9075:80
      - 749:443
    container_name: gep-configurations-web-v0.0.9-1
    networks:
      - app-network 
    restart: always
    tty: true
#The Database
  gep-configurations-db:
    image: mariadb:latest
    container_name: gep-configurations-db-v0.0.9-1
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=gep_configuration"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - app-network 
#Docker Networks
networks:
  app-network:
    driver: bridge
#Docker Volumes
volumes:
  dbdata:
